package org.roylance.yaclib.core.enums;

public class CommonTokens {
    public static final String DoNotAlterMessage = "// THIS FILE WAS AUTO-GENERATED. DO NOT ALTER!";
    public static final String AutoGeneratedAlteringOkay = "// This file was auto-generated, but can be altered. It will not be overwritten.";

    public static final String ControllerSuffix = "Controller";
    public static final String ActionSuffix = "Action";
    public static final String ServiceSuffix = "Service";

    public static final String ProtoMessageType = "MESSAGE";

    public static final String FactoryName = "Factory";
    public static final String ServiceName = "Service";
    public static final String UpperCaseRestName = "Rest";

    public static final String ServicesName = "services";
    public static final String RestName = "rest";
    public static final String UtilitiesName = "utilities";
    public static final String ServiceLocatorSingletonName = "ServiceLocator";
    public static final String ServiceLocatorName = "IServiceLocator";

    public static final String ServiceLocatorLocation = UtilitiesName + "." + ServiceLocatorSingletonName;

    public static final String ClientApi = "capi";
    public static final String ServerApi = "sapi";

    public static final String ApiName = "api";
    public static final String CSharpName = "csharp";
    public static final String PythonName = "python";
    public static final String JavaScriptName = "javascript";
    public static final String NodeModules = "node_modules";

    public static final String PascalApiName = "Api";

    public static final String HttpExecute = "IHttpExecute";
    public static final String HttpExecuteVariableName = "httpExecute";


}
