package org.roylance.yaclib.core.enums;

public class CommonTokens {
  public static final String DoNotAlterMessage = "// THIS FILE WAS AUTO-GENERATED. DO NOT ALTER!";
  public static final String AutoGeneratedAlteringOkay =
      "// This file was auto-generated, but can be altered. It will not be overwritten.";

  public static final String ControllerSuffix = "Controller";
  public static final String ActionSuffix = "Action";
  public static final String ServiceSuffix = "Service";

  public static final String ProtoMessageType = "MESSAGE";

  public static final String FactoryName = "Factory";
  public static final String ServiceName = "Service";
  public static final String UpperCaseRestName = "Rest";

  public static final String LibName = "lib";
  public static final String ServicesName = "services";
  public static final String RestName = "rest";
  public static final String UtilitiesName = "utilities";
  public static final String ServiceLocatorSingletonName = "ServiceLocator";
  public static final String ServiceLocatorName = "IServiceLocator";

  public static final String ServiceLocatorLocation =
      UtilitiesName + "." + ServiceLocatorSingletonName;

  public static final String ClientSuffix = "client";
  public static final String ServerSuffix = "server";
  public static final String JNIAffix = "jni";

  public static final String PythonSuffix = "py";
  public static final String CSharpSuffix = "cs";
  public static final String SwiftSuffix = "swift";
  public static final String JavaScriptSuffix = "js";
  public static final String DartSuffix = "js";

  public static final String NodeModules = "node_modules";

  public static final String HttpExecute = "IHttpExecute";
  public static final String HttpExecuteVariableName = "httpExecute";
}
