// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yaclib_viewmodel.proto

package org.roylance.yaclib;

public final class YaclibViewmodel {
  private YaclibViewmodel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code org.roylance.yaclib.BindingType}
   */
  public enum BindingType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>BINDING_INPUT = 0;</code>
     */
    BINDING_INPUT(0),
    /**
     * <code>BINDING_LABEL = 1;</code>
     */
    BINDING_LABEL(1),
    /**
     * <code>BINDING_SINGLE_SELECTION = 2;</code>
     */
    BINDING_SINGLE_SELECTION(2),
    /**
     * <code>BINDING_MULTI_SELECTION = 3;</code>
     */
    BINDING_MULTI_SELECTION(3),
    /**
     * <code>BINDING_CHECKBOX = 4;</code>
     */
    BINDING_CHECKBOX(4),
    /**
     * <code>BINDING_BUTTON = 5;</code>
     */
    BINDING_BUTTON(5),
    /**
     * <code>BINDING_IMAGE = 6;</code>
     */
    BINDING_IMAGE(6),
    /**
     * <code>BINDING_STATIC_TEXT = 7;</code>
     */
    BINDING_STATIC_TEXT(7),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>BINDING_INPUT = 0;</code>
     */
    public static final int BINDING_INPUT_VALUE = 0;
    /**
     * <code>BINDING_LABEL = 1;</code>
     */
    public static final int BINDING_LABEL_VALUE = 1;
    /**
     * <code>BINDING_SINGLE_SELECTION = 2;</code>
     */
    public static final int BINDING_SINGLE_SELECTION_VALUE = 2;
    /**
     * <code>BINDING_MULTI_SELECTION = 3;</code>
     */
    public static final int BINDING_MULTI_SELECTION_VALUE = 3;
    /**
     * <code>BINDING_CHECKBOX = 4;</code>
     */
    public static final int BINDING_CHECKBOX_VALUE = 4;
    /**
     * <code>BINDING_BUTTON = 5;</code>
     */
    public static final int BINDING_BUTTON_VALUE = 5;
    /**
     * <code>BINDING_IMAGE = 6;</code>
     */
    public static final int BINDING_IMAGE_VALUE = 6;
    /**
     * <code>BINDING_STATIC_TEXT = 7;</code>
     */
    public static final int BINDING_STATIC_TEXT_VALUE = 7;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static BindingType valueOf(int value) {
      return forNumber(value);
    }

    public static BindingType forNumber(int value) {
      switch (value) {
        case 0: return BINDING_INPUT;
        case 1: return BINDING_LABEL;
        case 2: return BINDING_SINGLE_SELECTION;
        case 3: return BINDING_MULTI_SELECTION;
        case 4: return BINDING_CHECKBOX;
        case 5: return BINDING_BUTTON;
        case 6: return BINDING_IMAGE;
        case 7: return BINDING_STATIC_TEXT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<BindingType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        BindingType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<BindingType>() {
            public BindingType findValueByNumber(int number) {
              return BindingType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.roylance.yaclib.YaclibViewmodel.getDescriptor().getEnumTypes().get(0);
    }

    private static final BindingType[] VALUES = values();

    public static BindingType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private BindingType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.roylance.yaclib.BindingType)
  }

  public interface ValidationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.roylance.yaclib.Validation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string regex = 1;</code>
     */
    java.lang.String getRegex();
    /**
     * <code>string regex = 1;</code>
     */
    com.google.protobuf.ByteString
        getRegexBytes();
  }
  /**
   * Protobuf type {@code org.roylance.yaclib.Validation}
   */
  public  static final class Validation extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.roylance.yaclib.Validation)
      ValidationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Validation.newBuilder() to construct.
    private Validation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Validation() {
      regex_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Validation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              regex_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.roylance.yaclib.YaclibViewmodel.internal_static_org_roylance_yaclib_Validation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.roylance.yaclib.YaclibViewmodel.internal_static_org_roylance_yaclib_Validation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.roylance.yaclib.YaclibViewmodel.Validation.class, org.roylance.yaclib.YaclibViewmodel.Validation.Builder.class);
    }

    public static final int REGEX_FIELD_NUMBER = 1;
    private volatile java.lang.Object regex_;
    /**
     * <code>string regex = 1;</code>
     */
    public java.lang.String getRegex() {
      java.lang.Object ref = regex_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        regex_ = s;
        return s;
      }
    }
    /**
     * <code>string regex = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRegexBytes() {
      java.lang.Object ref = regex_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        regex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRegexBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, regex_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRegexBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, regex_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.roylance.yaclib.YaclibViewmodel.Validation)) {
        return super.equals(obj);
      }
      org.roylance.yaclib.YaclibViewmodel.Validation other = (org.roylance.yaclib.YaclibViewmodel.Validation) obj;

      boolean result = true;
      result = result && getRegex()
          .equals(other.getRegex());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REGEX_FIELD_NUMBER;
      hash = (53 * hash) + getRegex().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.roylance.yaclib.YaclibViewmodel.Validation parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yaclib.YaclibViewmodel.Validation parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yaclib.YaclibViewmodel.Validation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yaclib.YaclibViewmodel.Validation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yaclib.YaclibViewmodel.Validation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yaclib.YaclibViewmodel.Validation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yaclib.YaclibViewmodel.Validation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.roylance.yaclib.YaclibViewmodel.Validation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.roylance.yaclib.YaclibViewmodel.Validation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.roylance.yaclib.YaclibViewmodel.Validation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.roylance.yaclib.YaclibViewmodel.Validation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.roylance.yaclib.YaclibViewmodel.Validation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.roylance.yaclib.YaclibViewmodel.Validation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.roylance.yaclib.Validation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.roylance.yaclib.Validation)
        org.roylance.yaclib.YaclibViewmodel.ValidationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.roylance.yaclib.YaclibViewmodel.internal_static_org_roylance_yaclib_Validation_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.roylance.yaclib.YaclibViewmodel.internal_static_org_roylance_yaclib_Validation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.roylance.yaclib.YaclibViewmodel.Validation.class, org.roylance.yaclib.YaclibViewmodel.Validation.Builder.class);
      }

      // Construct using org.roylance.yaclib.YaclibViewmodel.Validation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        regex_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.roylance.yaclib.YaclibViewmodel.internal_static_org_roylance_yaclib_Validation_descriptor;
      }

      public org.roylance.yaclib.YaclibViewmodel.Validation getDefaultInstanceForType() {
        return org.roylance.yaclib.YaclibViewmodel.Validation.getDefaultInstance();
      }

      public org.roylance.yaclib.YaclibViewmodel.Validation build() {
        org.roylance.yaclib.YaclibViewmodel.Validation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.roylance.yaclib.YaclibViewmodel.Validation buildPartial() {
        org.roylance.yaclib.YaclibViewmodel.Validation result = new org.roylance.yaclib.YaclibViewmodel.Validation(this);
        result.regex_ = regex_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.roylance.yaclib.YaclibViewmodel.Validation) {
          return mergeFrom((org.roylance.yaclib.YaclibViewmodel.Validation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.roylance.yaclib.YaclibViewmodel.Validation other) {
        if (other == org.roylance.yaclib.YaclibViewmodel.Validation.getDefaultInstance()) return this;
        if (!other.getRegex().isEmpty()) {
          regex_ = other.regex_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.roylance.yaclib.YaclibViewmodel.Validation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.roylance.yaclib.YaclibViewmodel.Validation) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object regex_ = "";
      /**
       * <code>string regex = 1;</code>
       */
      public java.lang.String getRegex() {
        java.lang.Object ref = regex_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          regex_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string regex = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRegexBytes() {
        java.lang.Object ref = regex_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          regex_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string regex = 1;</code>
       */
      public Builder setRegex(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        regex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string regex = 1;</code>
       */
      public Builder clearRegex() {
        
        regex_ = getDefaultInstance().getRegex();
        onChanged();
        return this;
      }
      /**
       * <code>string regex = 1;</code>
       */
      public Builder setRegexBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        regex_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.roylance.yaclib.Validation)
    }

    // @@protoc_insertion_point(class_scope:org.roylance.yaclib.Validation)
    private static final org.roylance.yaclib.YaclibViewmodel.Validation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.roylance.yaclib.YaclibViewmodel.Validation();
    }

    public static org.roylance.yaclib.YaclibViewmodel.Validation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Validation>
        PARSER = new com.google.protobuf.AbstractParser<Validation>() {
      public Validation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Validation(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Validation> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Validation> getParserForType() {
      return PARSER;
    }

    public org.roylance.yaclib.YaclibViewmodel.Validation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BindingDefinitionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.roylance.yaclib.BindingDefinition)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.org.roylance.yaclib.BindingType binding_type = 1;</code>
     */
    int getBindingTypeValue();
    /**
     * <code>.org.roylance.yaclib.BindingType binding_type = 1;</code>
     */
    org.roylance.yaclib.YaclibViewmodel.BindingType getBindingType();

    /**
     * <code>.org.roylance.yaclib.Validation validation = 2;</code>
     */
    boolean hasValidation();
    /**
     * <code>.org.roylance.yaclib.Validation validation = 2;</code>
     */
    org.roylance.yaclib.YaclibViewmodel.Validation getValidation();
    /**
     * <code>.org.roylance.yaclib.Validation validation = 2;</code>
     */
    org.roylance.yaclib.YaclibViewmodel.ValidationOrBuilder getValidationOrBuilder();

    /**
     * <code>string model_path = 3;</code>
     */
    java.lang.String getModelPath();
    /**
     * <code>string model_path = 3;</code>
     */
    com.google.protobuf.ByteString
        getModelPathBytes();
  }
  /**
   * Protobuf type {@code org.roylance.yaclib.BindingDefinition}
   */
  public  static final class BindingDefinition extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.roylance.yaclib.BindingDefinition)
      BindingDefinitionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BindingDefinition.newBuilder() to construct.
    private BindingDefinition(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BindingDefinition() {
      bindingType_ = 0;
      modelPath_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BindingDefinition(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              bindingType_ = rawValue;
              break;
            }
            case 18: {
              org.roylance.yaclib.YaclibViewmodel.Validation.Builder subBuilder = null;
              if (validation_ != null) {
                subBuilder = validation_.toBuilder();
              }
              validation_ = input.readMessage(org.roylance.yaclib.YaclibViewmodel.Validation.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(validation_);
                validation_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              modelPath_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.roylance.yaclib.YaclibViewmodel.internal_static_org_roylance_yaclib_BindingDefinition_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.roylance.yaclib.YaclibViewmodel.internal_static_org_roylance_yaclib_BindingDefinition_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.roylance.yaclib.YaclibViewmodel.BindingDefinition.class, org.roylance.yaclib.YaclibViewmodel.BindingDefinition.Builder.class);
    }

    public static final int BINDING_TYPE_FIELD_NUMBER = 1;
    private int bindingType_;
    /**
     * <code>.org.roylance.yaclib.BindingType binding_type = 1;</code>
     */
    public int getBindingTypeValue() {
      return bindingType_;
    }
    /**
     * <code>.org.roylance.yaclib.BindingType binding_type = 1;</code>
     */
    public org.roylance.yaclib.YaclibViewmodel.BindingType getBindingType() {
      org.roylance.yaclib.YaclibViewmodel.BindingType result = org.roylance.yaclib.YaclibViewmodel.BindingType.valueOf(bindingType_);
      return result == null ? org.roylance.yaclib.YaclibViewmodel.BindingType.UNRECOGNIZED : result;
    }

    public static final int VALIDATION_FIELD_NUMBER = 2;
    private org.roylance.yaclib.YaclibViewmodel.Validation validation_;
    /**
     * <code>.org.roylance.yaclib.Validation validation = 2;</code>
     */
    public boolean hasValidation() {
      return validation_ != null;
    }
    /**
     * <code>.org.roylance.yaclib.Validation validation = 2;</code>
     */
    public org.roylance.yaclib.YaclibViewmodel.Validation getValidation() {
      return validation_ == null ? org.roylance.yaclib.YaclibViewmodel.Validation.getDefaultInstance() : validation_;
    }
    /**
     * <code>.org.roylance.yaclib.Validation validation = 2;</code>
     */
    public org.roylance.yaclib.YaclibViewmodel.ValidationOrBuilder getValidationOrBuilder() {
      return getValidation();
    }

    public static final int MODEL_PATH_FIELD_NUMBER = 3;
    private volatile java.lang.Object modelPath_;
    /**
     * <code>string model_path = 3;</code>
     */
    public java.lang.String getModelPath() {
      java.lang.Object ref = modelPath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        modelPath_ = s;
        return s;
      }
    }
    /**
     * <code>string model_path = 3;</code>
     */
    public com.google.protobuf.ByteString
        getModelPathBytes() {
      java.lang.Object ref = modelPath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modelPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (bindingType_ != org.roylance.yaclib.YaclibViewmodel.BindingType.BINDING_INPUT.getNumber()) {
        output.writeEnum(1, bindingType_);
      }
      if (validation_ != null) {
        output.writeMessage(2, getValidation());
      }
      if (!getModelPathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, modelPath_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (bindingType_ != org.roylance.yaclib.YaclibViewmodel.BindingType.BINDING_INPUT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, bindingType_);
      }
      if (validation_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getValidation());
      }
      if (!getModelPathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, modelPath_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.roylance.yaclib.YaclibViewmodel.BindingDefinition)) {
        return super.equals(obj);
      }
      org.roylance.yaclib.YaclibViewmodel.BindingDefinition other = (org.roylance.yaclib.YaclibViewmodel.BindingDefinition) obj;

      boolean result = true;
      result = result && bindingType_ == other.bindingType_;
      result = result && (hasValidation() == other.hasValidation());
      if (hasValidation()) {
        result = result && getValidation()
            .equals(other.getValidation());
      }
      result = result && getModelPath()
          .equals(other.getModelPath());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BINDING_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + bindingType_;
      if (hasValidation()) {
        hash = (37 * hash) + VALIDATION_FIELD_NUMBER;
        hash = (53 * hash) + getValidation().hashCode();
      }
      hash = (37 * hash) + MODEL_PATH_FIELD_NUMBER;
      hash = (53 * hash) + getModelPath().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.roylance.yaclib.YaclibViewmodel.BindingDefinition parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yaclib.YaclibViewmodel.BindingDefinition parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yaclib.YaclibViewmodel.BindingDefinition parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yaclib.YaclibViewmodel.BindingDefinition parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yaclib.YaclibViewmodel.BindingDefinition parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yaclib.YaclibViewmodel.BindingDefinition parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yaclib.YaclibViewmodel.BindingDefinition parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.roylance.yaclib.YaclibViewmodel.BindingDefinition parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.roylance.yaclib.YaclibViewmodel.BindingDefinition parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.roylance.yaclib.YaclibViewmodel.BindingDefinition parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.roylance.yaclib.YaclibViewmodel.BindingDefinition parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.roylance.yaclib.YaclibViewmodel.BindingDefinition parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.roylance.yaclib.YaclibViewmodel.BindingDefinition prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.roylance.yaclib.BindingDefinition}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.roylance.yaclib.BindingDefinition)
        org.roylance.yaclib.YaclibViewmodel.BindingDefinitionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.roylance.yaclib.YaclibViewmodel.internal_static_org_roylance_yaclib_BindingDefinition_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.roylance.yaclib.YaclibViewmodel.internal_static_org_roylance_yaclib_BindingDefinition_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.roylance.yaclib.YaclibViewmodel.BindingDefinition.class, org.roylance.yaclib.YaclibViewmodel.BindingDefinition.Builder.class);
      }

      // Construct using org.roylance.yaclib.YaclibViewmodel.BindingDefinition.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        bindingType_ = 0;

        if (validationBuilder_ == null) {
          validation_ = null;
        } else {
          validation_ = null;
          validationBuilder_ = null;
        }
        modelPath_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.roylance.yaclib.YaclibViewmodel.internal_static_org_roylance_yaclib_BindingDefinition_descriptor;
      }

      public org.roylance.yaclib.YaclibViewmodel.BindingDefinition getDefaultInstanceForType() {
        return org.roylance.yaclib.YaclibViewmodel.BindingDefinition.getDefaultInstance();
      }

      public org.roylance.yaclib.YaclibViewmodel.BindingDefinition build() {
        org.roylance.yaclib.YaclibViewmodel.BindingDefinition result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.roylance.yaclib.YaclibViewmodel.BindingDefinition buildPartial() {
        org.roylance.yaclib.YaclibViewmodel.BindingDefinition result = new org.roylance.yaclib.YaclibViewmodel.BindingDefinition(this);
        result.bindingType_ = bindingType_;
        if (validationBuilder_ == null) {
          result.validation_ = validation_;
        } else {
          result.validation_ = validationBuilder_.build();
        }
        result.modelPath_ = modelPath_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.roylance.yaclib.YaclibViewmodel.BindingDefinition) {
          return mergeFrom((org.roylance.yaclib.YaclibViewmodel.BindingDefinition)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.roylance.yaclib.YaclibViewmodel.BindingDefinition other) {
        if (other == org.roylance.yaclib.YaclibViewmodel.BindingDefinition.getDefaultInstance()) return this;
        if (other.bindingType_ != 0) {
          setBindingTypeValue(other.getBindingTypeValue());
        }
        if (other.hasValidation()) {
          mergeValidation(other.getValidation());
        }
        if (!other.getModelPath().isEmpty()) {
          modelPath_ = other.modelPath_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.roylance.yaclib.YaclibViewmodel.BindingDefinition parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.roylance.yaclib.YaclibViewmodel.BindingDefinition) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int bindingType_ = 0;
      /**
       * <code>.org.roylance.yaclib.BindingType binding_type = 1;</code>
       */
      public int getBindingTypeValue() {
        return bindingType_;
      }
      /**
       * <code>.org.roylance.yaclib.BindingType binding_type = 1;</code>
       */
      public Builder setBindingTypeValue(int value) {
        bindingType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.org.roylance.yaclib.BindingType binding_type = 1;</code>
       */
      public org.roylance.yaclib.YaclibViewmodel.BindingType getBindingType() {
        org.roylance.yaclib.YaclibViewmodel.BindingType result = org.roylance.yaclib.YaclibViewmodel.BindingType.valueOf(bindingType_);
        return result == null ? org.roylance.yaclib.YaclibViewmodel.BindingType.UNRECOGNIZED : result;
      }
      /**
       * <code>.org.roylance.yaclib.BindingType binding_type = 1;</code>
       */
      public Builder setBindingType(org.roylance.yaclib.YaclibViewmodel.BindingType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        bindingType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.org.roylance.yaclib.BindingType binding_type = 1;</code>
       */
      public Builder clearBindingType() {
        
        bindingType_ = 0;
        onChanged();
        return this;
      }

      private org.roylance.yaclib.YaclibViewmodel.Validation validation_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.roylance.yaclib.YaclibViewmodel.Validation, org.roylance.yaclib.YaclibViewmodel.Validation.Builder, org.roylance.yaclib.YaclibViewmodel.ValidationOrBuilder> validationBuilder_;
      /**
       * <code>.org.roylance.yaclib.Validation validation = 2;</code>
       */
      public boolean hasValidation() {
        return validationBuilder_ != null || validation_ != null;
      }
      /**
       * <code>.org.roylance.yaclib.Validation validation = 2;</code>
       */
      public org.roylance.yaclib.YaclibViewmodel.Validation getValidation() {
        if (validationBuilder_ == null) {
          return validation_ == null ? org.roylance.yaclib.YaclibViewmodel.Validation.getDefaultInstance() : validation_;
        } else {
          return validationBuilder_.getMessage();
        }
      }
      /**
       * <code>.org.roylance.yaclib.Validation validation = 2;</code>
       */
      public Builder setValidation(org.roylance.yaclib.YaclibViewmodel.Validation value) {
        if (validationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          validation_ = value;
          onChanged();
        } else {
          validationBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaclib.Validation validation = 2;</code>
       */
      public Builder setValidation(
          org.roylance.yaclib.YaclibViewmodel.Validation.Builder builderForValue) {
        if (validationBuilder_ == null) {
          validation_ = builderForValue.build();
          onChanged();
        } else {
          validationBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaclib.Validation validation = 2;</code>
       */
      public Builder mergeValidation(org.roylance.yaclib.YaclibViewmodel.Validation value) {
        if (validationBuilder_ == null) {
          if (validation_ != null) {
            validation_ =
              org.roylance.yaclib.YaclibViewmodel.Validation.newBuilder(validation_).mergeFrom(value).buildPartial();
          } else {
            validation_ = value;
          }
          onChanged();
        } else {
          validationBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaclib.Validation validation = 2;</code>
       */
      public Builder clearValidation() {
        if (validationBuilder_ == null) {
          validation_ = null;
          onChanged();
        } else {
          validation_ = null;
          validationBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.org.roylance.yaclib.Validation validation = 2;</code>
       */
      public org.roylance.yaclib.YaclibViewmodel.Validation.Builder getValidationBuilder() {
        
        onChanged();
        return getValidationFieldBuilder().getBuilder();
      }
      /**
       * <code>.org.roylance.yaclib.Validation validation = 2;</code>
       */
      public org.roylance.yaclib.YaclibViewmodel.ValidationOrBuilder getValidationOrBuilder() {
        if (validationBuilder_ != null) {
          return validationBuilder_.getMessageOrBuilder();
        } else {
          return validation_ == null ?
              org.roylance.yaclib.YaclibViewmodel.Validation.getDefaultInstance() : validation_;
        }
      }
      /**
       * <code>.org.roylance.yaclib.Validation validation = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.roylance.yaclib.YaclibViewmodel.Validation, org.roylance.yaclib.YaclibViewmodel.Validation.Builder, org.roylance.yaclib.YaclibViewmodel.ValidationOrBuilder> 
          getValidationFieldBuilder() {
        if (validationBuilder_ == null) {
          validationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.roylance.yaclib.YaclibViewmodel.Validation, org.roylance.yaclib.YaclibViewmodel.Validation.Builder, org.roylance.yaclib.YaclibViewmodel.ValidationOrBuilder>(
                  getValidation(),
                  getParentForChildren(),
                  isClean());
          validation_ = null;
        }
        return validationBuilder_;
      }

      private java.lang.Object modelPath_ = "";
      /**
       * <code>string model_path = 3;</code>
       */
      public java.lang.String getModelPath() {
        java.lang.Object ref = modelPath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          modelPath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string model_path = 3;</code>
       */
      public com.google.protobuf.ByteString
          getModelPathBytes() {
        java.lang.Object ref = modelPath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          modelPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string model_path = 3;</code>
       */
      public Builder setModelPath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        modelPath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string model_path = 3;</code>
       */
      public Builder clearModelPath() {
        
        modelPath_ = getDefaultInstance().getModelPath();
        onChanged();
        return this;
      }
      /**
       * <code>string model_path = 3;</code>
       */
      public Builder setModelPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        modelPath_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.roylance.yaclib.BindingDefinition)
    }

    // @@protoc_insertion_point(class_scope:org.roylance.yaclib.BindingDefinition)
    private static final org.roylance.yaclib.YaclibViewmodel.BindingDefinition DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.roylance.yaclib.YaclibViewmodel.BindingDefinition();
    }

    public static org.roylance.yaclib.YaclibViewmodel.BindingDefinition getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BindingDefinition>
        PARSER = new com.google.protobuf.AbstractParser<BindingDefinition>() {
      public BindingDefinition parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BindingDefinition(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BindingDefinition> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BindingDefinition> getParserForType() {
      return PARSER;
    }

    public org.roylance.yaclib.YaclibViewmodel.BindingDefinition getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ServiceDefinitionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.roylance.yaclib.ServiceDefinition)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string full_name = 1;</code>
     */
    java.lang.String getFullName();
    /**
     * <code>string full_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getFullNameBytes();

    /**
     * <code>string view_model_property_name = 2;</code>
     */
    java.lang.String getViewModelPropertyName();
    /**
     * <code>string view_model_property_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getViewModelPropertyNameBytes();
  }
  /**
   * Protobuf type {@code org.roylance.yaclib.ServiceDefinition}
   */
  public  static final class ServiceDefinition extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.roylance.yaclib.ServiceDefinition)
      ServiceDefinitionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ServiceDefinition.newBuilder() to construct.
    private ServiceDefinition(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServiceDefinition() {
      fullName_ = "";
      viewModelPropertyName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ServiceDefinition(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              fullName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              viewModelPropertyName_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.roylance.yaclib.YaclibViewmodel.internal_static_org_roylance_yaclib_ServiceDefinition_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.roylance.yaclib.YaclibViewmodel.internal_static_org_roylance_yaclib_ServiceDefinition_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.roylance.yaclib.YaclibViewmodel.ServiceDefinition.class, org.roylance.yaclib.YaclibViewmodel.ServiceDefinition.Builder.class);
    }

    public static final int FULL_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object fullName_;
    /**
     * <code>string full_name = 1;</code>
     */
    public java.lang.String getFullName() {
      java.lang.Object ref = fullName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fullName_ = s;
        return s;
      }
    }
    /**
     * <code>string full_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFullNameBytes() {
      java.lang.Object ref = fullName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fullName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VIEW_MODEL_PROPERTY_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object viewModelPropertyName_;
    /**
     * <code>string view_model_property_name = 2;</code>
     */
    public java.lang.String getViewModelPropertyName() {
      java.lang.Object ref = viewModelPropertyName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        viewModelPropertyName_ = s;
        return s;
      }
    }
    /**
     * <code>string view_model_property_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getViewModelPropertyNameBytes() {
      java.lang.Object ref = viewModelPropertyName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        viewModelPropertyName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFullNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fullName_);
      }
      if (!getViewModelPropertyNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, viewModelPropertyName_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFullNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fullName_);
      }
      if (!getViewModelPropertyNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, viewModelPropertyName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.roylance.yaclib.YaclibViewmodel.ServiceDefinition)) {
        return super.equals(obj);
      }
      org.roylance.yaclib.YaclibViewmodel.ServiceDefinition other = (org.roylance.yaclib.YaclibViewmodel.ServiceDefinition) obj;

      boolean result = true;
      result = result && getFullName()
          .equals(other.getFullName());
      result = result && getViewModelPropertyName()
          .equals(other.getViewModelPropertyName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FULL_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getFullName().hashCode();
      hash = (37 * hash) + VIEW_MODEL_PROPERTY_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getViewModelPropertyName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.roylance.yaclib.YaclibViewmodel.ServiceDefinition parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yaclib.YaclibViewmodel.ServiceDefinition parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yaclib.YaclibViewmodel.ServiceDefinition parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yaclib.YaclibViewmodel.ServiceDefinition parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yaclib.YaclibViewmodel.ServiceDefinition parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yaclib.YaclibViewmodel.ServiceDefinition parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yaclib.YaclibViewmodel.ServiceDefinition parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.roylance.yaclib.YaclibViewmodel.ServiceDefinition parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.roylance.yaclib.YaclibViewmodel.ServiceDefinition parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.roylance.yaclib.YaclibViewmodel.ServiceDefinition parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.roylance.yaclib.YaclibViewmodel.ServiceDefinition parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.roylance.yaclib.YaclibViewmodel.ServiceDefinition parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.roylance.yaclib.YaclibViewmodel.ServiceDefinition prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.roylance.yaclib.ServiceDefinition}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.roylance.yaclib.ServiceDefinition)
        org.roylance.yaclib.YaclibViewmodel.ServiceDefinitionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.roylance.yaclib.YaclibViewmodel.internal_static_org_roylance_yaclib_ServiceDefinition_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.roylance.yaclib.YaclibViewmodel.internal_static_org_roylance_yaclib_ServiceDefinition_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.roylance.yaclib.YaclibViewmodel.ServiceDefinition.class, org.roylance.yaclib.YaclibViewmodel.ServiceDefinition.Builder.class);
      }

      // Construct using org.roylance.yaclib.YaclibViewmodel.ServiceDefinition.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        fullName_ = "";

        viewModelPropertyName_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.roylance.yaclib.YaclibViewmodel.internal_static_org_roylance_yaclib_ServiceDefinition_descriptor;
      }

      public org.roylance.yaclib.YaclibViewmodel.ServiceDefinition getDefaultInstanceForType() {
        return org.roylance.yaclib.YaclibViewmodel.ServiceDefinition.getDefaultInstance();
      }

      public org.roylance.yaclib.YaclibViewmodel.ServiceDefinition build() {
        org.roylance.yaclib.YaclibViewmodel.ServiceDefinition result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.roylance.yaclib.YaclibViewmodel.ServiceDefinition buildPartial() {
        org.roylance.yaclib.YaclibViewmodel.ServiceDefinition result = new org.roylance.yaclib.YaclibViewmodel.ServiceDefinition(this);
        result.fullName_ = fullName_;
        result.viewModelPropertyName_ = viewModelPropertyName_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.roylance.yaclib.YaclibViewmodel.ServiceDefinition) {
          return mergeFrom((org.roylance.yaclib.YaclibViewmodel.ServiceDefinition)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.roylance.yaclib.YaclibViewmodel.ServiceDefinition other) {
        if (other == org.roylance.yaclib.YaclibViewmodel.ServiceDefinition.getDefaultInstance()) return this;
        if (!other.getFullName().isEmpty()) {
          fullName_ = other.fullName_;
          onChanged();
        }
        if (!other.getViewModelPropertyName().isEmpty()) {
          viewModelPropertyName_ = other.viewModelPropertyName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.roylance.yaclib.YaclibViewmodel.ServiceDefinition parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.roylance.yaclib.YaclibViewmodel.ServiceDefinition) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object fullName_ = "";
      /**
       * <code>string full_name = 1;</code>
       */
      public java.lang.String getFullName() {
        java.lang.Object ref = fullName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fullName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string full_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFullNameBytes() {
        java.lang.Object ref = fullName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fullName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string full_name = 1;</code>
       */
      public Builder setFullName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fullName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string full_name = 1;</code>
       */
      public Builder clearFullName() {
        
        fullName_ = getDefaultInstance().getFullName();
        onChanged();
        return this;
      }
      /**
       * <code>string full_name = 1;</code>
       */
      public Builder setFullNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fullName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object viewModelPropertyName_ = "";
      /**
       * <code>string view_model_property_name = 2;</code>
       */
      public java.lang.String getViewModelPropertyName() {
        java.lang.Object ref = viewModelPropertyName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          viewModelPropertyName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string view_model_property_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getViewModelPropertyNameBytes() {
        java.lang.Object ref = viewModelPropertyName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          viewModelPropertyName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string view_model_property_name = 2;</code>
       */
      public Builder setViewModelPropertyName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        viewModelPropertyName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string view_model_property_name = 2;</code>
       */
      public Builder clearViewModelPropertyName() {
        
        viewModelPropertyName_ = getDefaultInstance().getViewModelPropertyName();
        onChanged();
        return this;
      }
      /**
       * <code>string view_model_property_name = 2;</code>
       */
      public Builder setViewModelPropertyNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        viewModelPropertyName_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.roylance.yaclib.ServiceDefinition)
    }

    // @@protoc_insertion_point(class_scope:org.roylance.yaclib.ServiceDefinition)
    private static final org.roylance.yaclib.YaclibViewmodel.ServiceDefinition DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.roylance.yaclib.YaclibViewmodel.ServiceDefinition();
    }

    public static org.roylance.yaclib.YaclibViewmodel.ServiceDefinition getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServiceDefinition>
        PARSER = new com.google.protobuf.AbstractParser<ServiceDefinition>() {
      public ServiceDefinition parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ServiceDefinition(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServiceDefinition> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ServiceDefinition> getParserForType() {
      return PARSER;
    }

    public org.roylance.yaclib.YaclibViewmodel.ServiceDefinition getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ViewModelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.roylance.yaclib.ViewModel)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code org.roylance.yaclib.ViewModel}
   */
  public  static final class ViewModel extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.roylance.yaclib.ViewModel)
      ViewModelOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ViewModel.newBuilder() to construct.
    private ViewModel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ViewModel() {
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ViewModel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.roylance.yaclib.YaclibViewmodel.internal_static_org_roylance_yaclib_ViewModel_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.roylance.yaclib.YaclibViewmodel.internal_static_org_roylance_yaclib_ViewModel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.roylance.yaclib.YaclibViewmodel.ViewModel.class, org.roylance.yaclib.YaclibViewmodel.ViewModel.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.roylance.yaclib.YaclibViewmodel.ViewModel)) {
        return super.equals(obj);
      }
      org.roylance.yaclib.YaclibViewmodel.ViewModel other = (org.roylance.yaclib.YaclibViewmodel.ViewModel) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.roylance.yaclib.YaclibViewmodel.ViewModel parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yaclib.YaclibViewmodel.ViewModel parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yaclib.YaclibViewmodel.ViewModel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yaclib.YaclibViewmodel.ViewModel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yaclib.YaclibViewmodel.ViewModel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yaclib.YaclibViewmodel.ViewModel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yaclib.YaclibViewmodel.ViewModel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.roylance.yaclib.YaclibViewmodel.ViewModel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.roylance.yaclib.YaclibViewmodel.ViewModel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.roylance.yaclib.YaclibViewmodel.ViewModel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.roylance.yaclib.YaclibViewmodel.ViewModel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.roylance.yaclib.YaclibViewmodel.ViewModel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.roylance.yaclib.YaclibViewmodel.ViewModel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.roylance.yaclib.ViewModel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.roylance.yaclib.ViewModel)
        org.roylance.yaclib.YaclibViewmodel.ViewModelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.roylance.yaclib.YaclibViewmodel.internal_static_org_roylance_yaclib_ViewModel_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.roylance.yaclib.YaclibViewmodel.internal_static_org_roylance_yaclib_ViewModel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.roylance.yaclib.YaclibViewmodel.ViewModel.class, org.roylance.yaclib.YaclibViewmodel.ViewModel.Builder.class);
      }

      // Construct using org.roylance.yaclib.YaclibViewmodel.ViewModel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.roylance.yaclib.YaclibViewmodel.internal_static_org_roylance_yaclib_ViewModel_descriptor;
      }

      public org.roylance.yaclib.YaclibViewmodel.ViewModel getDefaultInstanceForType() {
        return org.roylance.yaclib.YaclibViewmodel.ViewModel.getDefaultInstance();
      }

      public org.roylance.yaclib.YaclibViewmodel.ViewModel build() {
        org.roylance.yaclib.YaclibViewmodel.ViewModel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.roylance.yaclib.YaclibViewmodel.ViewModel buildPartial() {
        org.roylance.yaclib.YaclibViewmodel.ViewModel result = new org.roylance.yaclib.YaclibViewmodel.ViewModel(this);
        result.name_ = name_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.roylance.yaclib.YaclibViewmodel.ViewModel) {
          return mergeFrom((org.roylance.yaclib.YaclibViewmodel.ViewModel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.roylance.yaclib.YaclibViewmodel.ViewModel other) {
        if (other == org.roylance.yaclib.YaclibViewmodel.ViewModel.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.roylance.yaclib.YaclibViewmodel.ViewModel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.roylance.yaclib.YaclibViewmodel.ViewModel) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.roylance.yaclib.ViewModel)
    }

    // @@protoc_insertion_point(class_scope:org.roylance.yaclib.ViewModel)
    private static final org.roylance.yaclib.YaclibViewmodel.ViewModel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.roylance.yaclib.YaclibViewmodel.ViewModel();
    }

    public static org.roylance.yaclib.YaclibViewmodel.ViewModel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ViewModel>
        PARSER = new com.google.protobuf.AbstractParser<ViewModel>() {
      public ViewModel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ViewModel(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ViewModel> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ViewModel> getParserForType() {
      return PARSER;
    }

    public org.roylance.yaclib.YaclibViewmodel.ViewModel getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_roylance_yaclib_Validation_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_roylance_yaclib_Validation_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_roylance_yaclib_BindingDefinition_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_roylance_yaclib_BindingDefinition_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_roylance_yaclib_ServiceDefinition_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_roylance_yaclib_ServiceDefinition_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_roylance_yaclib_ViewModel_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_roylance_yaclib_ViewModel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026yaclib_viewmodel.proto\022\023org.roylance.y" +
      "aclib\"\033\n\nValidation\022\r\n\005regex\030\001 \001(\t\"\224\001\n\021B" +
      "indingDefinition\0226\n\014binding_type\030\001 \001(\0162 " +
      ".org.roylance.yaclib.BindingType\0223\n\nvali" +
      "dation\030\002 \001(\0132\037.org.roylance.yaclib.Valid" +
      "ation\022\022\n\nmodel_path\030\003 \001(\t\"H\n\021ServiceDefi" +
      "nition\022\021\n\tfull_name\030\001 \001(\t\022 \n\030view_model_" +
      "property_name\030\002 \001(\t\"\031\n\tViewModel\022\014\n\004name" +
      "\030\001 \001(\t*\304\001\n\013BindingType\022\021\n\rBINDING_INPUT\020" +
      "\000\022\021\n\rBINDING_LABEL\020\001\022\034\n\030BINDING_SINGLE_S",
      "ELECTION\020\002\022\033\n\027BINDING_MULTI_SELECTION\020\003\022" +
      "\024\n\020BINDING_CHECKBOX\020\004\022\022\n\016BINDING_BUTTON\020" +
      "\005\022\021\n\rBINDING_IMAGE\020\006\022\027\n\023BINDING_STATIC_T" +
      "EXT\020\007b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_roylance_yaclib_Validation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_roylance_yaclib_Validation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_roylance_yaclib_Validation_descriptor,
        new java.lang.String[] { "Regex", });
    internal_static_org_roylance_yaclib_BindingDefinition_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_roylance_yaclib_BindingDefinition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_roylance_yaclib_BindingDefinition_descriptor,
        new java.lang.String[] { "BindingType", "Validation", "ModelPath", });
    internal_static_org_roylance_yaclib_ServiceDefinition_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_roylance_yaclib_ServiceDefinition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_roylance_yaclib_ServiceDefinition_descriptor,
        new java.lang.String[] { "FullName", "ViewModelPropertyName", });
    internal_static_org_roylance_yaclib_ViewModel_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_roylance_yaclib_ViewModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_roylance_yaclib_ViewModel_descriptor,
        new java.lang.String[] { "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
