package org.roylance.yaclib.core.services.java.client

import org.roylance.common.service.IBuilder
import org.roylance.yaclib.YaclibModel
import org.roylance.yaclib.core.enums.CommonTokens
import org.roylance.yaclib.core.utilities.GradleUtilities
import org.roylance.yaclib.core.utilities.JavaUtilities

class GradleFileBuilder(private val projectInformation: YaclibModel.ProjectInformation,
                        private val projectName: String): IBuilder<YaclibModel.File> {
    private val InitialTemplate = """${CommonTokens.AutoGeneratedAlteringOkay}
buildscript {
    ext.kotlin_version = '${JavaUtilities.KotlinVersion}'
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath "org.jfrog.buildinfo:build-info-extractor-gradle:${JavaUtilities.ArtifactoryVersion}"
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:${JavaUtilities.BintrayVersion}'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${JavaUtilities.KotlinVersion}"
    }
}

group "$${JavaUtilities.GroupName}"
version "$${JavaUtilities.MajorName}.$${JavaUtilities.MinorName}"

apply plugin: 'java'
apply plugin: 'kotlin'
apply plugin: 'com.jfrog.bintray'
apply plugin: "com.jfrog.artifactory"
apply plugin: 'maven'
apply plugin: 'maven-publish'

sourceCompatibility = 1.7

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}

${buildUploadMethod()}

repositories {
    mavenCentral()
    maven { url '${JavaUtilities.DefaultRepository}'}
    ${GradleUtilities.buildRepository(projectInformation.mainDependency.mavenRepository)}
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '${JavaUtilities.JUnitVersion}'
    compile 'com.squareup.retrofit2:retrofit:${JavaUtilities.RetrofitVersion}'

    compile 'org.roylance:common:${JavaUtilities.RoylanceCommonVersion}'
    ${GradleUtilities.buildDependencies(projectInformation)}
}
"""

    override fun build(): YaclibModel.File {
        val returnFile = YaclibModel.File.newBuilder()
                .setFileToWrite(InitialTemplate)
                .setFileName("build")
                .setFileExtension(YaclibModel.FileExtension.GRADLE_EXT)
                .setFileUpdateType(YaclibModel.FileUpdateType.WRITE_IF_NOT_EXISTS)
                .setFullDirectoryLocation("")

        return returnFile.build()
    }

    private fun buildGithubRepo(): String {
        return projectInformation.mainDependency.githubRepo
    }

    private fun buildUploadMethod(): String {
        if (!projectInformation.mainDependency.hasMavenRepository()) {
            return ""
        }
        if (projectInformation.mainDependency.mavenRepository.repositoryType == YaclibModel.RepositoryType.ARTIFACTORY) {
            return buildArtifactory()
        }
        else if (projectInformation.mainDependency.mavenRepository.repositoryType == YaclibModel.RepositoryType.BINTRAY) {
            return buildBintray()
        }
        return buildStandardMaven()
    }

    private fun buildBintray(): String {
        return """
bintray {
    user = System.getenv('${JavaUtilities.BintrayUserName}')
    key = System.getenv('${JavaUtilities.BintrayKeyName}')
    publications = ['mavenJava']
    publish = true
    pkg {
        repo = "${projectInformation.mainDependency.mavenRepository.name}"
        name = "${projectInformation.mainDependency.group}.$projectName"
        userOrg = user
        licenses = ['${projectInformation.mainDependency.license}']
        labels = [rootProject.name]
        publicDownloadNumbers = true
        vcsUrl = '${buildGithubRepo()}'
        version {
            name = "${projectInformation.mainDependency.group}.$projectName"
        }
    }
}"""
    }

    private fun buildArtifactory(): String {
        return """artifactory {
    contextUrl = "${projectInformation.mainDependency.mavenRepository.url}"   // The base Artifactory URL if not overridden by the publisher/resolver
    publish {
        repository {
            repoKey = '${projectInformation.mainDependency.mavenRepository.name}'
            username = System.getenv('${JavaUtilities.ArtifactoryUserName}')
            password = System.getenv('${JavaUtilities.ArtifactoryPasswordName}')
            maven = true

        }
        defaults {
            publications('mavenJava')
            publishBuildInfo = true
            publishArtifacts = true
            properties = ['qa.level': 'basic', 'dev.team' : 'core']
            publishPom = true
        }
    }
    resolve {
        repository {
            repoKey = 'repo'
        }
    }
}
"""
    }

    private fun buildStandardMaven(): String {
        return """uploadArchives {
    repositories {
        mavenDeployer {
            repository(url: "${projectInformation.mainDependency.mavenRepository.url}") {
                authentication(userName: System.getenv('${JavaUtilities.StandardMavenUserName}'), password: System.getenv('${JavaUtilities.StandardMavenPassword}'))
            }
            pom.version = "$${JavaUtilities.MajorName}.$${JavaUtilities.MinorName}"
            pom.artifactId = "$projectName"
            pom.groupId = "${projectInformation.mainDependency.group}"
        }
    }
}
"""
    }
}