package org.roylance.yaclib.core.services.java.server

import org.roylance.common.service.IBuilder
import org.roylance.yaclib.YaclibModel
import org.roylance.yaclib.core.enums.CommonTokens

class CustomSetupBuilder : IBuilder<YaclibModel.File> {
    override fun build(): YaclibModel.File {
        val template = """#!/usr/bin/env bash
#${CommonTokens.AutoGeneratedAlteringOkay}
"""
        return YaclibModel.File.newBuilder()
                .setFileToWrite(template)
                .setFileName("custom")
                .setFileExtension(YaclibModel.FileExtension.SH_EXT)
                .setFileUpdateType(YaclibModel.FileUpdateType.WRITE_IF_NOT_EXISTS)
                .setFullDirectoryLocation("")
                .build()
    }

}