// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_model.proto

package org.roylance.yaclib;

public final class TestModel {
  private TestModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UIRandomFillerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.roylance.yaclib.UIRandomFiller)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string test = 1;</code>
     */
    java.lang.String getTest();
    /**
     * <code>string test = 1;</code>
     */
    com.google.protobuf.ByteString
        getTestBytes();

    /**
     * <code>string test_2 = 2;</code>
     */
    java.lang.String getTest2();
    /**
     * <code>string test_2 = 2;</code>
     */
    com.google.protobuf.ByteString
        getTest2Bytes();

    /**
     * <code>string test_3 = 3;</code>
     */
    java.lang.String getTest3();
    /**
     * <code>string test_3 = 3;</code>
     */
    com.google.protobuf.ByteString
        getTest3Bytes();
  }
  /**
   * Protobuf type {@code org.roylance.yaclib.UIRandomFiller}
   */
  public  static final class UIRandomFiller extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.roylance.yaclib.UIRandomFiller)
      UIRandomFillerOrBuilder {
    // Use UIRandomFiller.newBuilder() to construct.
    private UIRandomFiller(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UIRandomFiller() {
      test_ = "";
      test2_ = "";
      test3_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UIRandomFiller(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              test_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              test2_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              test3_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.roylance.yaclib.TestModel.internal_static_org_roylance_yaclib_UIRandomFiller_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.roylance.yaclib.TestModel.internal_static_org_roylance_yaclib_UIRandomFiller_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.roylance.yaclib.TestModel.UIRandomFiller.class, org.roylance.yaclib.TestModel.UIRandomFiller.Builder.class);
    }

    public static final int TEST_FIELD_NUMBER = 1;
    private volatile java.lang.Object test_;
    /**
     * <code>string test = 1;</code>
     */
    public java.lang.String getTest() {
      java.lang.Object ref = test_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        test_ = s;
        return s;
      }
    }
    /**
     * <code>string test = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTestBytes() {
      java.lang.Object ref = test_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        test_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEST_2_FIELD_NUMBER = 2;
    private volatile java.lang.Object test2_;
    /**
     * <code>string test_2 = 2;</code>
     */
    public java.lang.String getTest2() {
      java.lang.Object ref = test2_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        test2_ = s;
        return s;
      }
    }
    /**
     * <code>string test_2 = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTest2Bytes() {
      java.lang.Object ref = test2_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        test2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEST_3_FIELD_NUMBER = 3;
    private volatile java.lang.Object test3_;
    /**
     * <code>string test_3 = 3;</code>
     */
    public java.lang.String getTest3() {
      java.lang.Object ref = test3_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        test3_ = s;
        return s;
      }
    }
    /**
     * <code>string test_3 = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTest3Bytes() {
      java.lang.Object ref = test3_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        test3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTestBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, test_);
      }
      if (!getTest2Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, test2_);
      }
      if (!getTest3Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, test3_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTestBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, test_);
      }
      if (!getTest2Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, test2_);
      }
      if (!getTest3Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, test3_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.roylance.yaclib.TestModel.UIRandomFiller)) {
        return super.equals(obj);
      }
      org.roylance.yaclib.TestModel.UIRandomFiller other = (org.roylance.yaclib.TestModel.UIRandomFiller) obj;

      boolean result = true;
      result = result && getTest()
          .equals(other.getTest());
      result = result && getTest2()
          .equals(other.getTest2());
      result = result && getTest3()
          .equals(other.getTest3());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TEST_FIELD_NUMBER;
      hash = (53 * hash) + getTest().hashCode();
      hash = (37 * hash) + TEST_2_FIELD_NUMBER;
      hash = (53 * hash) + getTest2().hashCode();
      hash = (37 * hash) + TEST_3_FIELD_NUMBER;
      hash = (53 * hash) + getTest3().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.roylance.yaclib.TestModel.UIRandomFiller parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yaclib.TestModel.UIRandomFiller parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yaclib.TestModel.UIRandomFiller parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yaclib.TestModel.UIRandomFiller parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yaclib.TestModel.UIRandomFiller parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.roylance.yaclib.TestModel.UIRandomFiller parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.roylance.yaclib.TestModel.UIRandomFiller parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.roylance.yaclib.TestModel.UIRandomFiller parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.roylance.yaclib.TestModel.UIRandomFiller parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.roylance.yaclib.TestModel.UIRandomFiller parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.roylance.yaclib.TestModel.UIRandomFiller prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.roylance.yaclib.UIRandomFiller}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.roylance.yaclib.UIRandomFiller)
        org.roylance.yaclib.TestModel.UIRandomFillerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.roylance.yaclib.TestModel.internal_static_org_roylance_yaclib_UIRandomFiller_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.roylance.yaclib.TestModel.internal_static_org_roylance_yaclib_UIRandomFiller_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.roylance.yaclib.TestModel.UIRandomFiller.class, org.roylance.yaclib.TestModel.UIRandomFiller.Builder.class);
      }

      // Construct using org.roylance.yaclib.TestModel.UIRandomFiller.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        test_ = "";

        test2_ = "";

        test3_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.roylance.yaclib.TestModel.internal_static_org_roylance_yaclib_UIRandomFiller_descriptor;
      }

      public org.roylance.yaclib.TestModel.UIRandomFiller getDefaultInstanceForType() {
        return org.roylance.yaclib.TestModel.UIRandomFiller.getDefaultInstance();
      }

      public org.roylance.yaclib.TestModel.UIRandomFiller build() {
        org.roylance.yaclib.TestModel.UIRandomFiller result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.roylance.yaclib.TestModel.UIRandomFiller buildPartial() {
        org.roylance.yaclib.TestModel.UIRandomFiller result = new org.roylance.yaclib.TestModel.UIRandomFiller(this);
        result.test_ = test_;
        result.test2_ = test2_;
        result.test3_ = test3_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.roylance.yaclib.TestModel.UIRandomFiller) {
          return mergeFrom((org.roylance.yaclib.TestModel.UIRandomFiller)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.roylance.yaclib.TestModel.UIRandomFiller other) {
        if (other == org.roylance.yaclib.TestModel.UIRandomFiller.getDefaultInstance()) return this;
        if (!other.getTest().isEmpty()) {
          test_ = other.test_;
          onChanged();
        }
        if (!other.getTest2().isEmpty()) {
          test2_ = other.test2_;
          onChanged();
        }
        if (!other.getTest3().isEmpty()) {
          test3_ = other.test3_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.roylance.yaclib.TestModel.UIRandomFiller parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.roylance.yaclib.TestModel.UIRandomFiller) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object test_ = "";
      /**
       * <code>string test = 1;</code>
       */
      public java.lang.String getTest() {
        java.lang.Object ref = test_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          test_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string test = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTestBytes() {
        java.lang.Object ref = test_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          test_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string test = 1;</code>
       */
      public Builder setTest(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        test_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string test = 1;</code>
       */
      public Builder clearTest() {
        
        test_ = getDefaultInstance().getTest();
        onChanged();
        return this;
      }
      /**
       * <code>string test = 1;</code>
       */
      public Builder setTestBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        test_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object test2_ = "";
      /**
       * <code>string test_2 = 2;</code>
       */
      public java.lang.String getTest2() {
        java.lang.Object ref = test2_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          test2_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string test_2 = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTest2Bytes() {
        java.lang.Object ref = test2_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          test2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string test_2 = 2;</code>
       */
      public Builder setTest2(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        test2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string test_2 = 2;</code>
       */
      public Builder clearTest2() {
        
        test2_ = getDefaultInstance().getTest2();
        onChanged();
        return this;
      }
      /**
       * <code>string test_2 = 2;</code>
       */
      public Builder setTest2Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        test2_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object test3_ = "";
      /**
       * <code>string test_3 = 3;</code>
       */
      public java.lang.String getTest3() {
        java.lang.Object ref = test3_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          test3_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string test_3 = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTest3Bytes() {
        java.lang.Object ref = test3_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          test3_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string test_3 = 3;</code>
       */
      public Builder setTest3(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        test3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string test_3 = 3;</code>
       */
      public Builder clearTest3() {
        
        test3_ = getDefaultInstance().getTest3();
        onChanged();
        return this;
      }
      /**
       * <code>string test_3 = 3;</code>
       */
      public Builder setTest3Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        test3_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org.roylance.yaclib.UIRandomFiller)
    }

    // @@protoc_insertion_point(class_scope:org.roylance.yaclib.UIRandomFiller)
    private static final org.roylance.yaclib.TestModel.UIRandomFiller DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.roylance.yaclib.TestModel.UIRandomFiller();
    }

    public static org.roylance.yaclib.TestModel.UIRandomFiller getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UIRandomFiller>
        PARSER = new com.google.protobuf.AbstractParser<UIRandomFiller>() {
      public UIRandomFiller parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UIRandomFiller(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UIRandomFiller> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UIRandomFiller> getParserForType() {
      return PARSER;
    }

    public org.roylance.yaclib.TestModel.UIRandomFiller getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UITestRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.roylance.yaclib.UITestRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string token = 1;</code>
     */
    java.lang.String getToken();
    /**
     * <code>string token = 1;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <code>string context = 2;</code>
     */
    java.lang.String getContext();
    /**
     * <code>string context = 2;</code>
     */
    com.google.protobuf.ByteString
        getContextBytes();
  }
  /**
   * Protobuf type {@code org.roylance.yaclib.UITestRequest}
   */
  public  static final class UITestRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.roylance.yaclib.UITestRequest)
      UITestRequestOrBuilder {
    // Use UITestRequest.newBuilder() to construct.
    private UITestRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UITestRequest() {
      token_ = "";
      context_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UITestRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              context_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.roylance.yaclib.TestModel.internal_static_org_roylance_yaclib_UITestRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.roylance.yaclib.TestModel.internal_static_org_roylance_yaclib_UITestRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.roylance.yaclib.TestModel.UITestRequest.class, org.roylance.yaclib.TestModel.UITestRequest.Builder.class);
    }

    public static final int TOKEN_FIELD_NUMBER = 1;
    private volatile java.lang.Object token_;
    /**
     * <code>string token = 1;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>string token = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTEXT_FIELD_NUMBER = 2;
    private volatile java.lang.Object context_;
    /**
     * <code>string context = 2;</code>
     */
    public java.lang.String getContext() {
      java.lang.Object ref = context_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        context_ = s;
        return s;
      }
    }
    /**
     * <code>string context = 2;</code>
     */
    public com.google.protobuf.ByteString
        getContextBytes() {
      java.lang.Object ref = context_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        context_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, token_);
      }
      if (!getContextBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, context_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, token_);
      }
      if (!getContextBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, context_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.roylance.yaclib.TestModel.UITestRequest)) {
        return super.equals(obj);
      }
      org.roylance.yaclib.TestModel.UITestRequest other = (org.roylance.yaclib.TestModel.UITestRequest) obj;

      boolean result = true;
      result = result && getToken()
          .equals(other.getToken());
      result = result && getContext()
          .equals(other.getContext());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (37 * hash) + CONTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getContext().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.roylance.yaclib.TestModel.UITestRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yaclib.TestModel.UITestRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yaclib.TestModel.UITestRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yaclib.TestModel.UITestRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yaclib.TestModel.UITestRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.roylance.yaclib.TestModel.UITestRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.roylance.yaclib.TestModel.UITestRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.roylance.yaclib.TestModel.UITestRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.roylance.yaclib.TestModel.UITestRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.roylance.yaclib.TestModel.UITestRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.roylance.yaclib.TestModel.UITestRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.roylance.yaclib.UITestRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.roylance.yaclib.UITestRequest)
        org.roylance.yaclib.TestModel.UITestRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.roylance.yaclib.TestModel.internal_static_org_roylance_yaclib_UITestRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.roylance.yaclib.TestModel.internal_static_org_roylance_yaclib_UITestRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.roylance.yaclib.TestModel.UITestRequest.class, org.roylance.yaclib.TestModel.UITestRequest.Builder.class);
      }

      // Construct using org.roylance.yaclib.TestModel.UITestRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        token_ = "";

        context_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.roylance.yaclib.TestModel.internal_static_org_roylance_yaclib_UITestRequest_descriptor;
      }

      public org.roylance.yaclib.TestModel.UITestRequest getDefaultInstanceForType() {
        return org.roylance.yaclib.TestModel.UITestRequest.getDefaultInstance();
      }

      public org.roylance.yaclib.TestModel.UITestRequest build() {
        org.roylance.yaclib.TestModel.UITestRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.roylance.yaclib.TestModel.UITestRequest buildPartial() {
        org.roylance.yaclib.TestModel.UITestRequest result = new org.roylance.yaclib.TestModel.UITestRequest(this);
        result.token_ = token_;
        result.context_ = context_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.roylance.yaclib.TestModel.UITestRequest) {
          return mergeFrom((org.roylance.yaclib.TestModel.UITestRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.roylance.yaclib.TestModel.UITestRequest other) {
        if (other == org.roylance.yaclib.TestModel.UITestRequest.getDefaultInstance()) return this;
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        if (!other.getContext().isEmpty()) {
          context_ = other.context_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.roylance.yaclib.TestModel.UITestRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.roylance.yaclib.TestModel.UITestRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>string token = 1;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string token = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token = 1;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string token = 1;</code>
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>string token = 1;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object context_ = "";
      /**
       * <code>string context = 2;</code>
       */
      public java.lang.String getContext() {
        java.lang.Object ref = context_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          context_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string context = 2;</code>
       */
      public com.google.protobuf.ByteString
          getContextBytes() {
        java.lang.Object ref = context_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          context_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string context = 2;</code>
       */
      public Builder setContext(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        context_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string context = 2;</code>
       */
      public Builder clearContext() {
        
        context_ = getDefaultInstance().getContext();
        onChanged();
        return this;
      }
      /**
       * <code>string context = 2;</code>
       */
      public Builder setContextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        context_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org.roylance.yaclib.UITestRequest)
    }

    // @@protoc_insertion_point(class_scope:org.roylance.yaclib.UITestRequest)
    private static final org.roylance.yaclib.TestModel.UITestRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.roylance.yaclib.TestModel.UITestRequest();
    }

    public static org.roylance.yaclib.TestModel.UITestRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UITestRequest>
        PARSER = new com.google.protobuf.AbstractParser<UITestRequest>() {
      public UITestRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UITestRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UITestRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UITestRequest> getParserForType() {
      return PARSER;
    }

    public org.roylance.yaclib.TestModel.UITestRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UITestResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.roylance.yaclib.UITestResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string info = 1;</code>
     */
    java.lang.String getInfo();
    /**
     * <code>string info = 1;</code>
     */
    com.google.protobuf.ByteString
        getInfoBytes();

    /**
     * <code>string something_else = 2;</code>
     */
    java.lang.String getSomethingElse();
    /**
     * <code>string something_else = 2;</code>
     */
    com.google.protobuf.ByteString
        getSomethingElseBytes();
  }
  /**
   * Protobuf type {@code org.roylance.yaclib.UITestResponse}
   */
  public  static final class UITestResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.roylance.yaclib.UITestResponse)
      UITestResponseOrBuilder {
    // Use UITestResponse.newBuilder() to construct.
    private UITestResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UITestResponse() {
      info_ = "";
      somethingElse_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UITestResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              info_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              somethingElse_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.roylance.yaclib.TestModel.internal_static_org_roylance_yaclib_UITestResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.roylance.yaclib.TestModel.internal_static_org_roylance_yaclib_UITestResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.roylance.yaclib.TestModel.UITestResponse.class, org.roylance.yaclib.TestModel.UITestResponse.Builder.class);
    }

    public static final int INFO_FIELD_NUMBER = 1;
    private volatile java.lang.Object info_;
    /**
     * <code>string info = 1;</code>
     */
    public java.lang.String getInfo() {
      java.lang.Object ref = info_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        info_ = s;
        return s;
      }
    }
    /**
     * <code>string info = 1;</code>
     */
    public com.google.protobuf.ByteString
        getInfoBytes() {
      java.lang.Object ref = info_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        info_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOMETHING_ELSE_FIELD_NUMBER = 2;
    private volatile java.lang.Object somethingElse_;
    /**
     * <code>string something_else = 2;</code>
     */
    public java.lang.String getSomethingElse() {
      java.lang.Object ref = somethingElse_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        somethingElse_ = s;
        return s;
      }
    }
    /**
     * <code>string something_else = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSomethingElseBytes() {
      java.lang.Object ref = somethingElse_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        somethingElse_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getInfoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, info_);
      }
      if (!getSomethingElseBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, somethingElse_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getInfoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, info_);
      }
      if (!getSomethingElseBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, somethingElse_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.roylance.yaclib.TestModel.UITestResponse)) {
        return super.equals(obj);
      }
      org.roylance.yaclib.TestModel.UITestResponse other = (org.roylance.yaclib.TestModel.UITestResponse) obj;

      boolean result = true;
      result = result && getInfo()
          .equals(other.getInfo());
      result = result && getSomethingElse()
          .equals(other.getSomethingElse());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INFO_FIELD_NUMBER;
      hash = (53 * hash) + getInfo().hashCode();
      hash = (37 * hash) + SOMETHING_ELSE_FIELD_NUMBER;
      hash = (53 * hash) + getSomethingElse().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.roylance.yaclib.TestModel.UITestResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yaclib.TestModel.UITestResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yaclib.TestModel.UITestResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.roylance.yaclib.TestModel.UITestResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.roylance.yaclib.TestModel.UITestResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.roylance.yaclib.TestModel.UITestResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.roylance.yaclib.TestModel.UITestResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.roylance.yaclib.TestModel.UITestResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.roylance.yaclib.TestModel.UITestResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.roylance.yaclib.TestModel.UITestResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.roylance.yaclib.TestModel.UITestResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.roylance.yaclib.UITestResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.roylance.yaclib.UITestResponse)
        org.roylance.yaclib.TestModel.UITestResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.roylance.yaclib.TestModel.internal_static_org_roylance_yaclib_UITestResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.roylance.yaclib.TestModel.internal_static_org_roylance_yaclib_UITestResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.roylance.yaclib.TestModel.UITestResponse.class, org.roylance.yaclib.TestModel.UITestResponse.Builder.class);
      }

      // Construct using org.roylance.yaclib.TestModel.UITestResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        info_ = "";

        somethingElse_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.roylance.yaclib.TestModel.internal_static_org_roylance_yaclib_UITestResponse_descriptor;
      }

      public org.roylance.yaclib.TestModel.UITestResponse getDefaultInstanceForType() {
        return org.roylance.yaclib.TestModel.UITestResponse.getDefaultInstance();
      }

      public org.roylance.yaclib.TestModel.UITestResponse build() {
        org.roylance.yaclib.TestModel.UITestResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.roylance.yaclib.TestModel.UITestResponse buildPartial() {
        org.roylance.yaclib.TestModel.UITestResponse result = new org.roylance.yaclib.TestModel.UITestResponse(this);
        result.info_ = info_;
        result.somethingElse_ = somethingElse_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.roylance.yaclib.TestModel.UITestResponse) {
          return mergeFrom((org.roylance.yaclib.TestModel.UITestResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.roylance.yaclib.TestModel.UITestResponse other) {
        if (other == org.roylance.yaclib.TestModel.UITestResponse.getDefaultInstance()) return this;
        if (!other.getInfo().isEmpty()) {
          info_ = other.info_;
          onChanged();
        }
        if (!other.getSomethingElse().isEmpty()) {
          somethingElse_ = other.somethingElse_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.roylance.yaclib.TestModel.UITestResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.roylance.yaclib.TestModel.UITestResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object info_ = "";
      /**
       * <code>string info = 1;</code>
       */
      public java.lang.String getInfo() {
        java.lang.Object ref = info_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          info_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string info = 1;</code>
       */
      public com.google.protobuf.ByteString
          getInfoBytes() {
        java.lang.Object ref = info_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          info_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string info = 1;</code>
       */
      public Builder setInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        info_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string info = 1;</code>
       */
      public Builder clearInfo() {
        
        info_ = getDefaultInstance().getInfo();
        onChanged();
        return this;
      }
      /**
       * <code>string info = 1;</code>
       */
      public Builder setInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        info_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object somethingElse_ = "";
      /**
       * <code>string something_else = 2;</code>
       */
      public java.lang.String getSomethingElse() {
        java.lang.Object ref = somethingElse_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          somethingElse_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string something_else = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSomethingElseBytes() {
        java.lang.Object ref = somethingElse_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          somethingElse_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string something_else = 2;</code>
       */
      public Builder setSomethingElse(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        somethingElse_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string something_else = 2;</code>
       */
      public Builder clearSomethingElse() {
        
        somethingElse_ = getDefaultInstance().getSomethingElse();
        onChanged();
        return this;
      }
      /**
       * <code>string something_else = 2;</code>
       */
      public Builder setSomethingElseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        somethingElse_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org.roylance.yaclib.UITestResponse)
    }

    // @@protoc_insertion_point(class_scope:org.roylance.yaclib.UITestResponse)
    private static final org.roylance.yaclib.TestModel.UITestResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.roylance.yaclib.TestModel.UITestResponse();
    }

    public static org.roylance.yaclib.TestModel.UITestResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UITestResponse>
        PARSER = new com.google.protobuf.AbstractParser<UITestResponse>() {
      public UITestResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UITestResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UITestResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UITestResponse> getParserForType() {
      return PARSER;
    }

    public org.roylance.yaclib.TestModel.UITestResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_roylance_yaclib_UIRandomFiller_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_roylance_yaclib_UIRandomFiller_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_roylance_yaclib_UITestRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_roylance_yaclib_UITestRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_roylance_yaclib_UITestResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_roylance_yaclib_UITestResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020test_model.proto\022\023org.roylance.yaclib\"" +
      ">\n\016UIRandomFiller\022\014\n\004test\030\001 \001(\t\022\016\n\006test_" +
      "2\030\002 \001(\t\022\016\n\006test_3\030\003 \001(\t\"/\n\rUITestRequest" +
      "\022\r\n\005token\030\001 \001(\t\022\017\n\007context\030\002 \001(\t\"6\n\016UITe" +
      "stResponse\022\014\n\004info\030\001 \001(\t\022\026\n\016something_el" +
      "se\030\002 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_roylance_yaclib_UIRandomFiller_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_roylance_yaclib_UIRandomFiller_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_roylance_yaclib_UIRandomFiller_descriptor,
        new java.lang.String[] { "Test", "Test2", "Test3", });
    internal_static_org_roylance_yaclib_UITestRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_roylance_yaclib_UITestRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_roylance_yaclib_UITestRequest_descriptor,
        new java.lang.String[] { "Token", "Context", });
    internal_static_org_roylance_yaclib_UITestResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_roylance_yaclib_UITestResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_roylance_yaclib_UITestResponse_descriptor,
        new java.lang.String[] { "Info", "SomethingElse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
